config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  namespace :admin do
    resources :users
  end
  resources :users ,only: [:new,:create,:show,:edit,:update]
  resources :sessions ,only: [:new,:create,:destroy]
  resources :tasks ,only: [:index,:new,:create,:show,:edit,:update,:destroy]
end


# root GET    /                                                                                        tasks#index
#                     tasks GET    /tasks(.:format)                                                                         tasks#index
#                           POST   /tasks(.:format)                                                                         tasks#create
#                  new_task GET    /tasks/new(.:format)                                                                     tasks#new
#                 edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
#                      task GET    /tasks/:id(.:format)                                                                     tasks#show
#                           PATCH  /tasks/:id(.:format)                                                                     tasks#update
#                           PUT    /tasks/:id(.:format)                                                                     tasks#update
#                           DELETE /tasks/:id(.:format)                                                                     tasks#destroy


# admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#             POST   /admin/users(.:format)                                                                   admin/users#create
# new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
# edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#  admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#             PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#             PUT    /admin/users/:id(.:format)                                                               admin/users#update
#             DELETE /admin/users/:id(.:format)                                                               admin/users#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :tasklabels, dependent: :destroy
  has_many :tasks, through: :tasklabels
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  scope :search_title, ->title {where("title LIKE ?","%#{title}%")}
  scope :search_status, ->status {where(status: status)}
  enum priority:{低: 0,中: 1,高: 2}
  belongs_to :user
  has_many :tasklabels, dependent: :destroy
  has_many :labels, through: :tasklabels
end

app/models/tasklabel.rb
class Tasklabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  validates :name ,presence: true
  validates :email ,presence: true, uniqueness: true
  validates :password ,presence: true
  has_many :tasks, dependent: :destroy
  has_secure_password


  before_destroy :admin_destroy
  before_update :admin_update

  private
  def admin_destroy
    if User.where(admin:"true").count == 1 && self.admin == true
        throw :abort
    end
  end

  def admin_update
    if User.where(admin:"true").count == 1 && self.admin == false && User.where(admin:"true") == self
        throw :abort
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_required

  def index
    @user = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path,notice:"ユーザーを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path,notice:"ユーザーを削除しました"
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:admin)
  end

  def admin_required
    redirect_to tasks_path,notice:"管理者以外はアクセスできません" unless current_user.admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

before_action :login_required
  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :login_required, only: [:new, :create]

  def new
    redirect_to tasks_path if current_user
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
      @task = current_user.tasks.includes(:user)
      @task = @task.page(params[:page]).per(5)
    case params[:sort]
    when "ラベル検索" then
      @label = Tasklabel.where(label_id: params[:label_id])
      @label = @label.pluck(:task_id)
      @task = @task.where(id: @label)
    when "検索" then
      if params[:title].blank?
        @task = @task.search_status(params[:status])
      elsif params[:status].blank?
        @task = @task.search_title(params[:title])
      else
        @task = @task.search_title(params[:title]).search_status(params[:status])
      end
    when "limit" then
      @task = @task.order(limit: :desc)
    when "create" then
      @task = @task.order(created_at: :desc)
    when "priority" then
      @task = @task.order(priority: :desc)
    else
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to root_path,notice:"タスクを追加しました"
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to root_path,notice:"タスクを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path,notice:"タスクを削除しました"
  end

  private
  def task_params
    params.require(:task).permit(:title,:content,:limit,:status,:priority,label_ids:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :login_required, only: [:new, :create]

  def new
    redirect_to tasks_path if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      render :new
    end
  end

  def show
    redirect_to tasks_path,notice:"アクセスできません" unless current_user.id == params[:id].to_i
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def admin_user?
    current_user.admin.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>admin_edit</h1>
<%= form_with(model:@user,url:admin_user_path,local: true) do |form| %>
  <%= form.label :name , "名前"%>
  <%= form.text_field :name%>
  <%= form.label :email , "メールアドレス"%>
  <%= form.text_field :email%>
  <%= form.label :password , "パスワード"%>
  <%= form.password_field :password%>
  <%= form.label :admin , "権限"%>
  <%= form.select :admin,[["一般","false"],["管理者","ture"]] %>
  <%= form.submit "登録する"%>
<% end %>

app/views/admin/users/index.html.erb
<h1>admin_user_index</h1>
<h3><%=link_to 'ユーザー作成' ,new_admin_user_path%></h3>
<table class="table">
  <tr>
    <th>権限</th>
    <th>名前</th>
    <th>メールアドレス</th>
    <th>タスク数</th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
  </tr>
<% @user.each do |user| %>
  <tr>
    <td><%=user.admin%></td>
    <td><%=user.name%></td>
    <td><%=user.email%></td>
    <td><%=user.tasks.count%></td>
    <td><%=link_to '詳細' ,admin_user_path(user.id),class:'show'%></td>
    <td><%=link_to '編集' ,edit_admin_user_path(user.id),class:'edit'%></td>
    <td><%=link_to '削除' ,admin_user_path(user.id),method: :delete,data:{confirm:'削除します'},class:'destroy'%></td>
  </tr>
<% end %>
</table>

app/views/admin/users/new.html.erb
<h1>admin_new</h1>
<h1>新規登録</h1>
<%= form_with(model:@user,url:admin_users_path,local: true) do |form| %>
  <%= form.label :name , "名前"%>
  <%= form.text_field :name%>
  <%= form.label :email , "メールアドレス"%>
  <%= form.text_field :email%>
  <%= form.label :password , "パスワード"%>
  <%= form.password_field :password%>
  <%= form.label :admin , "権限"%>
  <%= form.select :admin,[["一般","false"],["管理者","ture"]] %>
  <%= form.submit "登録する"%>
<% end %>

app/views/admin/users/show.html.erb
<h1>admin_show</h1>

<h1>マイページ  <%=@user.name%></h1>


<table class="table">
  <tr>
    <th>投稿者</th>
    <th>タスク名</th>
    <th>内容</th>
    <th>ステータス</th>
    <th>
      <%= link_to '優先度', tasks_path(sort:"priority") %>
    </th>
    <th><%= link_to '終了期限', tasks_path(sort:"limit") %></th>
    <th><%= link_to '登録日時', tasks_path(sort:"create") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%@user.tasks.each do |task|%>
  <tr>
    <td><%=task.user.name%></td>
    <td class="title"><%=task.title%></td>
    <td><%=task.content%></td>
    <td><%=task.status%></td>
    <td><%=task.priority%></td>
    <td class="limit"><%=task.limit.strftime('%Y/%m/%d')%></td>
    <td class="create"><%=task.created_at.strftime('%Y/%m/%d')%></td>
    <td><%= link_to '詳細', task_path(task.id), class:"label label-warning"%></td>
    <td><%= link_to '編集', edit_task_path(task.id), class:"label label-success"%></td>
    <td><%= link_to '削除', task_path(task.id), class:"label label-danger",method: :delete ,data: { confirm: '削除します' } %>
  </tr>
<%end%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <ul>
      <li><%= current_user.name%>でログイン中</li>
      <li><s><%= link_to 'アカウント登録', new_user_path %></s>アクセス制限</li>
      <li><s><%= link_to 'ログイン', new_session_path %></s>アクセス制限</li>
      <li><%= link_to 'タスク一覧', tasks_path %></li>
      <li><%= link_to 'プロフィール', user_path(current_user.id) %></li>
      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
      <% if admin_user? %>
        <li><%= link_to 'ユーザー一覧（管理者用）', admin_users_path %></li>
        <% else %>
        <li><s><%= link_to 'ユーザー一覧（管理者用）', admin_users_path %></s>アクセス制限</li>
      <% end %>
    </ul>
    <% else %>
    <ul>
      <li>ログインしていません</li>
      <li><%= link_to 'アカウント登録', new_user_path %></li>
      <li><%= link_to 'ログイン', new_session_path %></li>
      <li><s><%= link_to 'タスク一覧', tasks_path %></s>アクセス制限</li>
      <li><s><%= link_to 'プロフィール' %></s>リンクなし</li>
      <li><s><%= link_to "ログアウト" %></s>リンクなし</li>
      <li><s><%= link_to 'ユーザー一覧（管理者用）', admin_users_path %></s>アクセス制限</li>
    </ul>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true )  do |form| %>
  <div class="form_container">
    <div class="form-group">
    <%= form.label :title, "タスク名"%>
    <%= form.text_field :title ,class: "form-control"%>
    </div>
    <div class="form-group">
    <%= form.label :content, "内容"%>
    <%= form.text_area :content ,class: "form-control"%>
    </div>
    <div class="form-group">
    <%= form.label :status, "ステータス"%>
    <%= form.select :status,[["未着手","未着手"],["着手中","着手中"],["完了","完了"]] %>
    </div>
    <div class="form-group">
    <%= form.label :priority, "優先度"%>
    <%= form.select :priority,[["低","低"],["中","中"],["高","高"]] %>
    </div>
    <div class="form-group">
    <%= form.label :limit, "期限"%>
    <%= form.date_field :limit %>
    </div>

    <% Label.all.each do |label|%>
    <%= form.check_box :label_ids, { multiple: true, checked: @task.labels.find_by(id: label.id).present?, include_hidden: false }, label[:id] %>
    <%= form.label :label_ids, label.name, value: label[:id] %>
    <% end %>

    <%= form.submit "登録する",data: { confirm: 'この内容で登録します' } %>
<% end %>
    <br>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @task.errors.full_messages.each do |msg| %>
          <li class="list-group-item list-group-item-warning"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<br>
<%= link_to '一覧', root_path %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= render 'form'%>

app/views/tasks/index.html.erb
<h1>タスク管理 <%=current_user.name%></h1>
<%=notice%>
<br>
<div class="">
  <%= form_with url: tasks_path,method: :get, local: true do |f| %>
    <span>タスク名</span>
    <%= f.text_field :title ,placeholder:"検索"%>
    <span>ステータス</span>
    <%= f.select :status,[[],["未着手","未着手"],["着手中","着手中"],["完了","完了"]] %>
    <%= f.submit "検索",name: :sort,value: "検索" %>
    <span>ラベル</span>
    <%= f.select :label_id, Label.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
    <%= f.submit "ラベル検索",name: :sort,value: "ラベル検索" %>
  <% end %>
</div>
<br>
<div class="">
<table class="table">
  <tr>
    <th>投稿者</th>
    <th>タスク名</th>
    <th>内容</th>
    <th>ステータス</th>
    <th>
      <%= link_to '優先度', tasks_path(sort:"priority") %>
    </th>
    <th><%= link_to '終了期限', tasks_path(sort:"limit") %></th>
    <th><%= link_to '登録日時', tasks_path(sort:"create") %></th>
    <th>タスク編集</th>
  </tr>
<%@task.each do |task|%>
  <tr>
    <td><%=task.user.name%></td>
    <td class="task-title"><%=task.title%></td>
    <td><%=task.content%></td>
    <td><%=task.status%></td>
    <td><%=task.priority%></td>
    <td class="limit"><%=task.limit.strftime('%Y/%m/%d')%></td>
    <td class="create"><%=task.created_at.strftime('%Y/%m/%d')%></td>
    <td>
      <%= link_to '詳細', task_path(task.id), class:"label label-warning task-show"%>
      <%= link_to '編集', edit_task_path(task.id), class:"label label-success task-edit"%>
      <%= link_to '削除', task_path(task.id), class:"label label-danger task-delete",method: :delete ,data: { confirm: '削除します' } %>
    </td>
  </tr>
<%end%>
</table>
</div>

<%= paginate @task %>
<br>
<%= link_to '登録', new_task_path %>
<%= link_to 'TOP', tasks_path %>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>
<br>
<%= render 'form'%>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
<br>
<table class="table">
  <tr>
    <th>タスク名</th>
    <th>内容</th>
  </tr>
  <tr>
    <td><%=@task.title%></td>
    <td><%=@task.content%></td>
  </tr>
</table>
<h2>登録ラベル</h2>
<% @task.labels.each do |label| %>
<p><%=label.name%></p>
<% end %>

<br>
<%= link_to '一覧', root_path %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with(model:@user,local: true) do |form| %>
  <%= form.label :name , "名前"%>
  <%= form.text_field :name%>
  <%= form.label :email , "メールアドレス"%>
  <%= form.text_field :email%>
  <%= form.label :password , "パスワード"%>
  <%= form.password_field :password%>
  <%= form.label :admin , "権限"%>
  <%= form.select :admin,[["一般","false"],["管理者","ture"]] %>
  <%= form.submit "登録する"%>
<% end %>

app/views/users/show.html.erb
<h1>マイページ  <%=current_user.name%></h1>